# f-gan Lightning Module specific configurations

_target_: src.models.GAN.LitFGAN

latent_dim: 100
img_size: 784
hidden_dim: 64
output_dim: 1
lr: 0.0002
chosen_divergence: "KLD"
batch_size: 64
adam_beta_one: 0.5
noise_coefficient: 1.0
anealing_factor: 0.9