#specify whatever configurations here

_target_: src.models.one_class.LitDeepOCSVM

#is preset for mnist data
input_dim: 784
hidden_dim: 64
rep_dim: 8
l2_weight: 1e-2
lr: 1e-2


#Genralizable Model Architecture
#input_size: 784
#layer_1_size: 64
#layer_2_size: 32
#layer_3_size: 16
#layer_4_size: 8  