_target_: src.models.walter_gan.WalterGAN
div: "GAN"
nc: 1
nz: 100
ngf: 64
ndf: 64
lr: 0.0002
beta1: 0.5
beta2: 0.999
use_noise: True
noise_bandwith: 0.01
noise_annealing: 1.
c: 0.01
use_disc_reg: False
reg_gama: 0.1
reg_annealing: 1.