defaults:
  - default.yaml

#FOLLOWING THREE ARE GENERAL ONES GIVEN BY TEMPLATE; THEY ARE GOOD TO KEEP FOR ANY 
watch_model:
  _target_: src.callbacks.wandb_callbacks.WatchModel
  log: "all"
  log_freq: 100

upload_code_as_artifact:
  _target_: src.callbacks.wandb_callbacks.UploadCodeAsArtifact
  code_dir: ${work_dir}/src

upload_ckpts_as_artifact:
  _target_: src.callbacks.wandb_callbacks.UploadCheckpointsAsArtifact
  ckpt_dir: "checkpoints/"
  upload_best_only: True

 #HERE WE GIVE CONFIGS TO MODEL-SPECIFIC CALLBACKS WE CREATED
 #FOR INSTANCE, IN F-GAN TRAINING, WE WOULD WANT TO LOG GENERATED IMAGES, SO WE CREATE THAT CALLBACK
 #MIGHT WANT TO CALL IT f-gan_log_generated_images SO WE KNOW WHAT MODEL THE CALLBACK IS REFERRING TO?  
log_generated_images:
  _target_: src.callbacks.wandb_callbacks.LogGeneratedImages
  num_samples: 8

#THEN WE MIGHT HAVE A CALLBACK FOR THE ONE-CLASS, LIKE ONE TO SHOW PREDICTIONS WITH CORRESPONDING EXAMPLES
#one-class_log_predictions:
  #_target_: src.callbacks.wandb_callbakcs.OneClassLogPredictions
  #num_samples: 5
  #AND SO ON


