#FOR WHATEVER DATASETS WE USE AND SUBSEQUENTLY CONSTRUCT PYTORCH DATASET AND PL DATAMODULES

_target_: src.datamodules.datasetB.DatasetB

data_dir: ${data_dir} # data_dir is specified in config.yaml
batch_size: 64
train_val_test_split: [55_000, 5_000, 10_000] # OR WHATEVER
num_workers: 0
pin_memory: False
#AND SO ON 